# -*- coding: utf-8 -*-
"""DrissionPage Anti-Detection Crawler Scaffolder."""
from pathlib import Path
from typing import Dict, Any
from jinja2 import Template
from scrapeclaw.synthesizer.scaffolders.base import BaseScaffolder

DRISSION_TEMPLATE = """# ==============================================================================
# Autonomous DrissionPage Crawler Generated by ScrapeClaw
# Target URL: {{ target_url }}
# Underlying API: {{ target_api_url }}
# ==============================================================================
import argparse
import json
import logging
import os
import sys
import time
from typing import List, Dict, Any

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("DrissionSpider")

try:
    from DrissionPage import SessionPage
except ImportError:
    SessionPage = None


class DrissionCrawler:
    def __init__(self, session_file: str = ""):
        self.api_url = "{{ target_api_url }}"
        self.method = "{{ method }}"
        self.headers = {{ minimal_headers | tojson }}
        self.cookies = {{ minimal_cookies | tojson }}

        # Session Lineage 2.0: Dynamic credential file override
        if session_file and os.path.exists(session_file):
            try:
                with open(session_file, "r", encoding="utf-8") as sf:
                    sdata = json.load(sf)
                    for c in sdata.get("cookies", []):
                        if "name" in c and "value" in c:
                            self.cookies[c["name"]] = c["value"]
                logger.info(f"Loaded dynamic session credentials from {session_file}")
            except Exception as e:
                logger.warning(f"Failed to load session file {session_file}: {e}")

        if SessionPage is None:
            raise RuntimeError("DrissionPage is not installed. Install via: pip install DrissionPage")

        self.page = SessionPage()
        for k, v in self.headers.items():
            self.page.set.headers({k: v})
        if self.cookies:
            self.page.set.cookies(self.cookies)

    def fetch_page(self, page_num: int) -> List[Dict[str, Any]]:
        params = {{ query_params | tojson }}
        {% if pagination_param %}
        params["{{ pagination_param }}"] = page_num * {{ pagination_step }}
        {% endif %}

        logger.info(f"Fetching page {page_num}...")
        if self.method == "GET":
            resp = self.page.get(self.api_url, params=params)
        else:
            resp = self.page.post(self.api_url, data=params)

        try:
            data = resp.json
        except Exception:
            logger.warning(f"Response is not JSON: {resp.text[:200]}")
            return []

        items = data
        for part in "{{ data_jsonpath }}".split('.'):
            if not part:
                continue
            if part.endswith("[*]"):
                key = part[:-3]
                if isinstance(items, dict):
                    items = items.get(key, [])
            elif part == "[*]":
                if isinstance(items, list):
                    items = [sub for sub in items if sub]
            else:
                if isinstance(items, dict):
                    items = items.get(part, [])
                elif isinstance(items, list):
                    items = [sub.get(part) for sub in items if isinstance(sub, dict) and part in sub]

        if isinstance(items, list):
            return items
        if isinstance(items, dict):
            return [items]
        return []

    def crawl(self, max_pages: int = 5) -> List[Dict[str, Any]]:
        all_results = []
        for p in range(1, max_pages + 1):
            items = self.fetch_page(p)
            if not items:
                logger.info(f"Page {p} returned empty data. Pagination finished.")
                break
            all_results.extend(items)
            time.sleep(0.5)
        return all_results

    def close(self):
        try:
            self.page.close()
        except Exception:
            pass


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-pages", type=int, default=1)
    parser.add_argument("--output", type=str, default="")
    parser.add_argument("--session", type=str, default="", help="Path to dynamic session file to override cookies")
    args = parser.parse_args()

    crawler = DrissionCrawler(session_file=args.session)
    try:
        results = crawler.crawl(max_pages=args.max_pages)
        print(json.dumps(results, ensure_ascii=False))
        if args.output:
            with open(args.output, "w", encoding="utf-8") as f:
                json.dump(results, f, ensure_ascii=False, indent=2)
    finally:
        crawler.close()


if __name__ == "__main__":
    main()
"""


class DrissionScaffolder(BaseScaffolder):
    """Generates an anti-detection crawler powered by DrissionPage."""

    def render_code(self, spec: Dict[str, Any]) -> str:
        tmpl = Template(DRISSION_TEMPLATE)
        return tmpl.render(
            target_url=spec.get("target_url", ""),
            target_api_url=spec.get("target_api_url", ""),
            method=spec.get("method", "GET"),
            minimal_headers=spec.get("minimal_headers", {}),
            minimal_cookies=spec.get("minimal_cookies", {}),
            query_params=spec.get("query_params", {}),
            pagination_param=spec.get("pagination_param", "page"),
            pagination_step=spec.get("pagination_step", 1),
            data_jsonpath=spec.get("data_jsonpath", "data"),
        )

    def generate(self, spec: Dict[str, Any], output_path: Path) -> Dict[str, Path]:
        code = self.render_code(spec)
        target_file = output_path
        if target_file.is_dir() or target_file.suffix != ".py":
            target_file = target_file / "drission_spider.py"
        target_file.parent.mkdir(parents=True, exist_ok=True)
        target_file.write_text(code, encoding="utf-8")
        return {target_file.name: target_file}
