# -*- coding: utf-8 -*-
"""HTTPX Single-File Asynchronous Crawler Scaffolder (with JS Reverse Engineering Signature Support)."""
from pathlib import Path
from typing import Dict, Any
from jinja2 import Template
from scrapeclaw.synthesizer.scaffolders.base import BaseScaffolder

TEMPLATE = """# ==============================================================================
# Autonomous Crawler Generated by ScrapeClaw
# Target URL: {{ target_url }}
# Underlying API: {{ target_api_url }}
# ==============================================================================
import asyncio
import os
import argparse
import logging
import json
import sys
import subprocess
from pathlib import Path
from typing import AsyncGenerator, Dict, List, Any
import httpx
from pydantic import BaseModel
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("ScrapeClawSpider")

class ScrapeClawSpider:
    def __init__(self, concurrency: int = 3, timeout: float = 15.0, session_file: str = ""):
        self.api_url = "{{ target_api_url }}"
        self.method = "{{ method }}"
        self.headers = {{ minimal_headers | tojson }}
        self.cookies = {{ minimal_cookies | tojson }}

        # Session Lineage 2.0: Dynamic credential file override
        if session_file and os.path.exists(session_file):
            try:
                with open(session_file, "r", encoding="utf-8") as sf:
                    sdata = json.load(sf)
                    for c in sdata.get("cookies", []):
                        if "name" in c and "value" in c:
                            self.cookies[c["name"]] = c["value"]
                logger.info(f"Loaded dynamic session credentials from {session_file}")
            except Exception as e:
                logger.warning(f"Failed to load session file {session_file}: {e}")

        self.semaphore = asyncio.Semaphore(concurrency)
        self.client = httpx.AsyncClient(
            headers=self.headers,
            cookies=self.cookies,
            timeout=timeout,
            follow_redirects=True,
            verify=False
        )

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=2, max=10),
        retry=retry_if_exception_type((httpx.RequestError, httpx.HTTPStatusError))
    )
    async def fetch_page(self, page_num: int) -> List[Dict[str, Any]]:
        async with self.semaphore:
            params = {{ query_params | tojson }}
            req_headers = dict(self.headers)
            {% if pagination_param %}
            params["{{ pagination_param }}"] = page_num * {{ pagination_step }}
            {% endif %}

            {% if sign_js_code or sign_header_name or sign_param_name %}
            # Dynamic client signature generation (Story 12 JS Reverse Engineering)
            try:
                sign_script = Path(__file__).parent / "sign.js"
                if sign_script.exists():
                    res = subprocess.run(
                        ["node", str(sign_script), json.dumps(params, ensure_ascii=False)],
                        capture_output=True,
                        text=True,
                        timeout=5.0,
                        check=True
                    )
                    sig = res.stdout.strip()
                    {% if sign_header_name %}
                    req_headers["{{ sign_header_name }}"] = sig
                    self.headers["{{ sign_header_name }}"] = sig
                    {% endif %}
                    {% if sign_param_name %}
                    params["{{ sign_param_name }}"] = sig
                    {% endif %}
            except Exception as e:
                logger.warning(f"Failed to generate dynamic signature: {e}")
            {% endif %}

            logger.info(f"Fetching page {page_num}...")
            if self.method == "GET":
                resp = await self.client.get(self.api_url, params=params, headers=req_headers)
            else:
                resp = await self.client.post(self.api_url, params=params, headers=req_headers)
            
            resp.raise_for_status()
            data = resp.json()
            
            items = data
            for part in "{{ data_jsonpath }}".split('.'):
                if not part:
                    continue
                if part.endswith("[*]"):
                    key = part[:-3]
                    if isinstance(items, dict):
                        items = items.get(key, [])
                elif part == "[*]":
                    if isinstance(items, list):
                        items = [sub for sub in items if sub]
                else:
                    if isinstance(items, dict):
                        items = items.get(part, [])
                    elif isinstance(items, list):
                        items = [sub.get(part) for sub in items if isinstance(sub, dict) and part in sub]
            
            if isinstance(items, list):
                return items
            if isinstance(items, dict):
                return [items]
            return []

    async def crawl(self, max_pages: int = 5) -> AsyncGenerator[Dict[str, Any], None]:
        for p in range(1, max_pages + 1):
            items = await self.fetch_page(p)
            if not items:
                logger.info(f"Page {p} returned empty data. Pagination finished.")
                break
            for item in items:
                yield item
            await asyncio.sleep(0.5)

    async def close(self):
        await self.client.aclose()

async def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-pages", type=int, default=1)
    parser.add_argument("--output", type=str, default="")
    parser.add_argument("--session", type=str, default="", help="Path to dynamic session file to override cookies")
    args = parser.parse_args()

    spider = ScrapeClawSpider(session_file=args.session)
    results = []
    try:
        async for item in spider.crawl(max_pages=args.max_pages):
            results.append(item)
        print(json.dumps(results, ensure_ascii=False))
        if args.output:
            with open(args.output, "w", encoding="utf-8") as f:
                json.dump(results, f, ensure_ascii=False, indent=2)
    finally:
        await spider.close()

if __name__ == "__main__":
    asyncio.run(main())
"""


class HttpxScaffolder(BaseScaffolder):
    """Generates a standalone, asynchronous Python script powered by httpx."""

    def render_code(self, spec: Dict[str, Any]) -> str:
        tmpl = Template(TEMPLATE)
        return tmpl.render(
            target_url=spec.get("target_url", ""),
            target_api_url=spec.get("target_api_url", ""),
            method=spec.get("method", "GET"),
            minimal_headers=spec.get("minimal_headers", {}),
            minimal_cookies=spec.get("minimal_cookies", {}),
            query_params=spec.get("query_params", {}),
            pagination_param=spec.get("pagination_param", "page"),
            pagination_step=spec.get("pagination_step", 1),
            data_jsonpath=spec.get("data_jsonpath", "data"),
            sign_js_code=spec.get("sign_js_code", ""),
            sign_header_name=spec.get("sign_header_name", ""),
            sign_param_name=spec.get("sign_param_name", ""),
        )

    def generate(self, spec: Dict[str, Any], output_path: Path) -> Dict[str, Path]:
        code = self.render_code(spec)
        target_file = output_path
        if target_file.is_dir() or target_file.suffix != ".py":
            target_file = target_file / "generated_spider.py"
        target_file.parent.mkdir(parents=True, exist_ok=True)
        target_file.write_text(code, encoding="utf-8")
        artifacts = {target_file.name: target_file}

        sign_code = spec.get("sign_js_code")
        if sign_code:
            sign_file = target_file.parent / spec.get("sign_js_file", "sign.js")
            sign_file.write_text(sign_code, encoding="utf-8")
            artifacts[sign_file.name] = sign_file

        return artifacts
