# -*- coding: utf-8 -*-
"""Playwright Anti-Detection & DOM-Rendering Crawler Scaffolder."""
from pathlib import Path
from typing import Dict, Any
from jinja2 import Template
from scrapeclaw.synthesizer.scaffolders.base import BaseScaffolder

PLAYWRIGHT_TEMPLATE = """# ==============================================================================
# Autonomous Playwright DOM Crawler Generated by ScrapeClaw
# Target URL: {{ target_url }}
# Mode: Browser DOM Automation & Dynamic Decryption Extraction
# ==============================================================================
import argparse
import asyncio
import json
import logging
import os
import sys
import time
from typing import List, Dict, Any

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("PlaywrightSpider")

try:
    from playwright.async_api import async_playwright
except ImportError:
    async_playwright = None


class PlaywrightCrawler:
    def __init__(self, target_url: str, session_file: str = "", headless: bool = True):
        self.target_url = target_url
        self.session_file = session_file
        self.headless = headless
        self.selector = "{{ item_selector | default('.el-table__row, .list-item, .item, tr, article, li', true) }}"

    async def run(self, max_pages: int = 1) -> List[Dict[str, Any]]:
        if async_playwright is None:
            raise RuntimeError("playwright is not installed. Install via: pip install playwright && playwright install chromium")

        all_results = []
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=self.headless)
            context_kwargs = {
                "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                "viewport": {"width": 1280, "height": 800}
            }
            if self.session_file and os.path.exists(self.session_file):
                try:
                    with open(self.session_file, "r", encoding="utf-8") as sf:
                        sdata = json.load(sf)
                        if isinstance(sdata, dict) and "cookies" in sdata:
                            pass
                    context_kwargs["storage_state"] = self.session_file
                    logger.info(f"Loaded storage state from {self.session_file}")
                except Exception as e:
                    logger.warning(f"Failed to load storage state: {e}")

            context = await browser.new_context(**context_kwargs)
            page = await context.new_page()

            try:
                logger.info(f"Navigating to {self.target_url}...")
                await page.goto(self.target_url, timeout=35000, wait_until="domcontentloaded")
                await asyncio.sleep(2.0)

                {% if search_keyword %}
                # Automated keyword query with Vue/React reactive event dispatching
                try:
                    search_input = await page.wait_for_selector("input[type='text'], input:not([type='hidden'])", timeout=5000)
                    if search_input:
                        await search_input.fill("{{ search_keyword }}")
                        await page.evaluate('''() => {
                            const inp = document.querySelector("input[type='text']:not([class*='yidun']), input:not([type='hidden'])");
                            if (inp) {
                                inp.dispatchEvent(new Event("input", { bubbles: true }));
                                inp.dispatchEvent(new Event("change", { bubbles: true }));
                            }
                            const btn = document.querySelector("button[type='submit'], .search-btn, button:has-text('搜索')");
                            if (btn) {
                                btn.removeAttribute("disabled");
                                btn.disabled = false;
                            }
                        }''')
                        await asyncio.sleep(0.5)
                        search_btn = await page.query_selector("button[type='submit'], .search-btn, button:has-text('搜索')")
                        if search_btn and await search_btn.is_enabled():
                            await search_btn.click()
                        else:
                            await search_input.press("Enter")
                        logger.info("Submitted search query for '{{ search_keyword }}'")
                        await asyncio.sleep(2.0)
                except Exception as e:
                    logger.warning(f"Search input interaction skipped: {e}")
                {% endif %}

                for page_idx in range(1, max_pages + 1):
                    logger.info(f"Extracting rendered elements from page {page_idx}...")
                    items = await page.evaluate('''() => {
                        const records = [];
                        const candidateSelectors = ['.list_body .left_body', '.left_body', '.el-table__row', '.bulletin-item', '.list-item', 'table tbody tr', '.content-item', 'li'];
                        let matched = [];
                        for (let sel of candidateSelectors) {
                            const found = document.querySelectorAll(sel);
                            if (found && found.length > 0) {
                                matched = found;
                                break;
                            }
                        }
                        if (matched.length === 0) {
                            matched = document.querySelectorAll("tr, article, li");
                        }

                        matched.forEach((el, index) => {
                            const text = el.innerText ? el.innerText.trim() : "";
                            if (!text || text.length < 5) return;

                            const links = el.querySelectorAll("a");
                            let primaryHref = "";
                            let linkTitle = "";
                            if (links.length > 0) {
                                primaryHref = links[0].href || "";
                                linkTitle = links[0].innerText ? links[0].innerText.trim() : "";
                            }

                            const lines = text.split("\\\\n").map(s => s.trim()).filter(s => s.length > 0);
                            const record = {
                                "id": index + 1,
                                "title": linkTitle || (lines.length > 0 ? lines[0] : "Item " + (index + 1)),
                                "content": lines.join(" | "),
                                "url": primaryHref || window.location.href
                            };
                            records.push(record);
                        });
                        return records;
                    }''')

                    if items:
                        all_results.extend(items)
                        logger.info(f"Extracted {len(items)} items from page {page_idx}")
                    else:
                        logger.info(f"No items matched on page {page_idx}")

                    if page_idx >= max_pages:
                        break

            finally:
                await browser.close()

        return all_results


def main():
    parser = argparse.ArgumentParser(description="Autonomous Playwright DOM Crawler")
    parser.add_argument("--max-pages", type=int, default=1)
    parser.add_argument("--output", type=str, default="")
    parser.add_argument("--session", type=str, default="", help="Path to session JSON file")
    parser.add_argument("--headed", action="store_true", help="Run browser in visible mode")
    args = parser.parse_args()

    crawler = PlaywrightCrawler(
        target_url="{{ target_url }}",
        session_file=args.session,
        headless=not args.headed
    )
    results = asyncio.run(crawler.run(max_pages=args.max_pages))
    print(json.dumps(results, ensure_ascii=False))

    if args.output:
        out_p = Path(args.output)
        out_p.parent.mkdir(parents=True, exist_ok=True)
        out_p.write_text(json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8")
        logger.info(f"Saved {len(results)} records to {args.output}")


if __name__ == "__main__":
    main()
"""


class PlaywrightScaffolder(BaseScaffolder):
    """Generates an anti-detection browser DOM crawler powered by Playwright."""

    def render_code(self, spec: Dict[str, Any]) -> str:
        tmpl = Template(PLAYWRIGHT_TEMPLATE)
        return tmpl.render(
            target_url=spec.get("target_url", ""),
            search_keyword=spec.get("search_keyword", ""),
            item_selector=spec.get("item_selector", "")
        )

    def generate(self, spec: Dict[str, Any], output_path: Path) -> Dict[str, Path]:
        code = self.render_code(spec)
        target_file = output_path
        if target_file.is_dir() or target_file.suffix != ".py":
            target_file = target_file / "playwright_spider.py"
        target_file.parent.mkdir(parents=True, exist_ok=True)
        target_file.write_text(code, encoding="utf-8")
        return {target_file.name: target_file}
