# -*- coding: utf-8 -*-
"""Scrapy Industrial Project Scaffolding Exporter."""
import re
from pathlib import Path
from typing import Dict, Any, List
from jinja2 import Template
from scrapeclaw.synthesizer.scaffolders.base import BaseScaffolder

SCRAPY_CFG_TEMPLATE = """# Automatically created by: ScrapeClaw
# For more information about the [deploy] section see:
# https://scrapyd.readthedocs.io/en/latest/deploy.html

[settings]
default = {{ project_name }}.settings

[deploy]
#url = http://localhost:6800/
project = {{ project_name }}
"""

SETTINGS_TEMPLATE = """# Scrapy settings for {{ project_name }} project
# Generated by ScrapeClaw Autonomous Synthesizer

BOT_NAME = "{{ project_name }}"

SPIDER_MODULES = ["{{ project_name }}.spiders"]
NEWSPIDER_MODULE = "{{ project_name }}.spiders"

USER_AGENT = "{{ user_agent }}"
ROBOTSTXT_OBEY = False
CONCURRENT_REQUESTS = 8
DOWNLOAD_DELAY = 0.5
CONCURRENT_REQUESTS_PER_DOMAIN = 4
COOKIES_ENABLED = True

DEFAULT_REQUEST_HEADERS = {{ minimal_headers | tojson }}

DOWNLOADER_MIDDLEWARES = {
    "{{ project_name }}.middlewares.SessionAuthMiddleware": 543,
}

ITEM_PIPELINES = {
    "{{ project_name }}.pipelines.JsonExportPipeline": 300,
}

REQUEST_FINGERPRINTER_IMPLEMENTATION = "2.7"
TWISTED_REACTOR = "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
FEED_EXPORT_ENCODING = "utf-8"
"""

ITEMS_TEMPLATE = """# Define here the models for your scraped items
import scrapy


class TargetItem(scrapy.Item):
    # Dynamic field container for extracted items
    {% for field in fields %}
    {{ field }} = scrapy.Field()
    {% endfor %}
    raw_data = scrapy.Field()
"""

MIDDLEWARES_TEMPLATE = """# Define here the models for your spider middleware
import json
import os
import logging
from scrapy import signals

logger = logging.getLogger(__name__)


class SessionAuthMiddleware:
    def __init__(self, session_file=None):
        self.session_file = session_file
        self.session_cookies = {}
        if session_file and os.path.exists(session_file):
            try:
                with open(session_file, "r", encoding="utf-8") as f:
                    sdata = json.load(f)
                    for c in sdata.get("cookies", []):
                        if "name" in c and "value" in c:
                            self.session_cookies[c["name"]] = c["value"]
                logger.info(f"SessionAuthMiddleware: Loaded {len(self.session_cookies)} cookies from {session_file}")
            except Exception as e:
                logger.warning(f"Failed to load session file {session_file}: {e}")

    @classmethod
    def from_crawler(cls, crawler):
        session_file = crawler.settings.get("SESSION_FILE") or getattr(crawler.spider, "session", None)
        return cls(session_file=session_file)

    def process_request(self, request, spider):
        if self.session_cookies:
            existing = request.cookies or {}
            merged = {**self.session_cookies, **existing}
            request.cookies = merged
        return None
"""

PIPELINES_TEMPLATE = """# Define your item pipelines here
import json
from pathlib import Path


class JsonExportPipeline:
    def open_spider(self, spider):
        self.items = []
        out_path = getattr(spider, "output", None) or "scraped_data.json"
        self.output_file = Path(out_path)

    def close_spider(self, spider):
        self.output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(self.output_file, "w", encoding="utf-8") as f:
            json.dump(self.items, f, ensure_ascii=False, indent=2)

    def process_item(self, item, spider):
        d = dict(item)
        if "raw_data" in d and len(d) > 1:
            del d["raw_data"]
        self.items.append(d)
        return item
"""

SPIDER_TEMPLATE = """# -*- coding: utf-8 -*-
import json
import urllib.parse
import scrapy
from ..items import TargetItem


class TargetSpider(scrapy.Spider):
    name = "{{ spider_name }}"
    allowed_domains = ["{{ domain }}"]
    api_url = "{{ target_api_url }}"
    method = "{{ method }}"
    headers = {{ minimal_headers | tojson }}
    cookies = {{ minimal_cookies | tojson }}
    base_params = {{ query_params | tojson }}
    pagination_param = "{{ pagination_param }}"
    pagination_step = {{ pagination_step }}
    data_jsonpath = "{{ data_jsonpath }}"

    def __init__(self, max_pages=5, session="", output="", *args, **kwargs):
        super(TargetSpider, self).__init__(*args, **kwargs)
        self.max_pages = int(max_pages)
        self.session = session
        self.output = output
        self.current_page = 1

    def start_requests(self):
        yield self._build_page_request(page_num=1)

    def _build_page_request(self, page_num: int):
        params = dict(self.base_params)
        if self.pagination_param:
            params[self.pagination_param] = page_num * self.pagination_step
        
        url = self.api_url
        if self.method.upper() == "GET" and params:
            qs = urllib.parse.urlencode(params)
            sep = "&" if "?" in url else "?"
            url = f"{url}{sep}{qs}"
            return scrapy.Request(
                url=url,
                method="GET",
                headers=self.headers,
                cookies=self.cookies,
                callback=self.parse,
                meta={"page_num": page_num},
                dont_filter=True,
            )
        else:
            return scrapy.FormRequest(
                url=url,
                method="POST",
                formdata={k: str(v) for k, v in params.items()},
                headers=self.headers,
                cookies=self.cookies,
                callback=self.parse,
                meta={"page_num": page_num},
                dont_filter=True,
            )

    def parse(self, response):
        try:
            data = json.loads(response.text)
        except Exception as e:
            self.logger.error(f"Failed to parse JSON response: {e}")
            return

        items = data
        for part in self.data_jsonpath.split("."):
            if not part:
                continue
            if part.endswith("[*]"):
                key = part[:-3]
                if isinstance(items, dict):
                    items = items.get(key, [])
            elif part == "[*]":
                if isinstance(items, list):
                    items = [sub for sub in items if sub]
            else:
                if isinstance(items, dict):
                    items = items.get(part, [])
                elif isinstance(items, list):
                    items = [sub.get(part) for sub in items if isinstance(sub, dict) and part in sub]

        record_list = []
        if isinstance(items, list):
            record_list = items
        elif isinstance(items, dict):
            record_list = [items]

        if not record_list:
            self.logger.info("No items found on current page. Pagination complete.")
            return

        for raw_item in record_list:
            item = TargetItem()
            item["raw_data"] = raw_item
            if isinstance(raw_item, dict):
                for k, v in raw_item.items():
                    item[k] = v
            yield item

        current_page = response.meta.get("page_num", 1)
        if current_page < self.max_pages and self.pagination_param:
            next_page = current_page + 1
            yield self._build_page_request(page_num=next_page)
"""


class ScrapyScaffolder(BaseScaffolder):
    """Generates an industrial-grade, multi-file Scrapy project scaffolding."""

    def _sanitize_name(self, name: str) -> str:
        clean = re.sub(r"[^a-zA-Z0-9_]", "_", name).strip("_").lower()
        if not clean or clean[0].isdigit():
            clean = "spider_" + clean
        return clean or "scrapy_project"

    def generate(self, spec: Dict[str, Any], output_path: Path) -> Dict[str, Path]:
        project_name = self._sanitize_name(spec.get("project_name", "scrapeclaw_project"))
        spider_name = self._sanitize_name(spec.get("spider_name", "target_spider"))

        # Determine target directory
        if output_path.suffix == ".py":
            project_dir = output_path.parent / (output_path.stem + "_scrapy")
        else:
            project_dir = output_path / project_name if output_path.name != project_name else output_path

        package_dir = project_dir / project_name
        spiders_dir = package_dir / "spiders"
        spiders_dir.mkdir(parents=True, exist_ok=True)

        target_api_url = spec.get("target_api_url", "")
        domain = ""
        try:
            from urllib.parse import urlparse
            domain = urlparse(target_api_url).hostname or ""
        except Exception:
            domain = "example.com"

        headers = spec.get("minimal_headers", {})
        user_agent = headers.get("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) ScrapeClawSpider/1.0")

        sample_fields = []
        if "sample_data" in spec and isinstance(spec["sample_data"], list) and spec["sample_data"]:
            first = spec["sample_data"][0]
            if isinstance(first, dict):
                sample_fields = [k for k in first.keys() if re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", k)]

        created_files = {}

        # 1. scrapy.cfg
        cfg_content = Template(SCRAPY_CFG_TEMPLATE).render(project_name=project_name)
        cfg_file = project_dir / "scrapy.cfg"
        cfg_file.write_text(cfg_content, encoding="utf-8")
        created_files["scrapy.cfg"] = cfg_file

        # 2. package __init__.py
        init_file = package_dir / "__init__.py"
        init_file.write_text("# -*- coding: utf-8 -*-\n", encoding="utf-8")
        created_files[f"{project_name}/__init__.py"] = init_file

        # 3. items.py
        items_content = Template(ITEMS_TEMPLATE).render(fields=sample_fields)
        items_file = package_dir / "items.py"
        items_file.write_text(items_content, encoding="utf-8")
        created_files[f"{project_name}/items.py"] = items_file

        # 4. settings.py
        settings_content = Template(SETTINGS_TEMPLATE).render(
            project_name=project_name,
            user_agent=user_agent,
            minimal_headers=headers,
        )
        settings_file = package_dir / "settings.py"
        settings_file.write_text(settings_content, encoding="utf-8")
        created_files[f"{project_name}/settings.py"] = settings_file

        # 5. middlewares.py
        middlewares_content = Template(MIDDLEWARES_TEMPLATE).render(project_name=project_name)
        middlewares_file = package_dir / "middlewares.py"
        middlewares_file.write_text(middlewares_content, encoding="utf-8")
        created_files[f"{project_name}/middlewares.py"] = middlewares_file

        # 6. pipelines.py
        pipelines_content = Template(PIPELINES_TEMPLATE).render(project_name=project_name)
        pipelines_file = package_dir / "pipelines.py"
        pipelines_file.write_text(pipelines_content, encoding="utf-8")
        created_files[f"{project_name}/pipelines.py"] = pipelines_file

        # 7. spiders/__init__.py
        spiders_init = spiders_dir / "__init__.py"
        spiders_init.write_text("# -*- coding: utf-8 -*-\n", encoding="utf-8")
        created_files[f"{project_name}/spiders/__init__.py"] = spiders_init

        # 8. spiders/<spider_name>.py
        spider_content = Template(SPIDER_TEMPLATE).render(
            spider_name=spider_name,
            domain=domain,
            target_api_url=target_api_url,
            method=spec.get("method", "GET"),
            minimal_headers=headers,
            minimal_cookies=spec.get("minimal_cookies", {}),
            query_params=spec.get("query_params", {}),
            pagination_param=spec.get("pagination_param", "page"),
            pagination_step=spec.get("pagination_step", 1),
            data_jsonpath=spec.get("data_jsonpath", "data"),
        )
        spider_file = spiders_dir / f"{spider_name}.py"
        spider_file.write_text(spider_content, encoding="utf-8")
        created_files[f"{project_name}/spiders/{spider_name}.py"] = spider_file

        return created_files
